### ISSUE TITLE
Can not export env variables

### ISSUE THREAD

**Issue by fxdgear** [shockone/black-screen#124]
`export foo='bar'`

![ss](https://files.app.net/7frccSkiC.png)

**Comment by shockone** [comment]
Hey, @fxdgear. Thanks for your feedback. We use a custom shell, which is very primitive at the moment. When we come to the point of improving it, we'll definitely support variables exporting.

**Comment by fxdgear** [comment]
Np. I just wanted to make sure you had a place to track it. :)

**Comment by coxley** [comment]
When you say special shell, no zsh or bash support?

**Comment by shockone** [comment]
@coxley starting yesterday the commands are executed in your login shell, whether it's BASH, ZSH, or anything else. So, you can use redirections, pipes, and all the good stuff. However, they're executed in a non-interactive mode, so commands are independent, that's why exporting a variable doesn't work. Although, you can do the usual `VAR_NAME=value command` to change it for the command.

**Comment by coxley** [comment]
Ah, so all built-ins are thrown away. :(

**Comment by jerch** [comment]
@shockone Any plans so far to solve this? Main problem I see with building a very own shell is this: People want to use their beloved shell env just within an even better env with more capabilities (hey comon, how about using javascript/node directly in blackscreen? Oh wait I want to use python as well, and ruby omg ... :o)
This is btw the most interesting part of blackscreen - how to cope with all those native shell envs to keep up with peoples' expectations? A dirty solution might be to use some "expect" scripts with the native shells and map them into blackscreen. But this will be cumbersome since even a simple bash env with readline support is hard due to various locale settings and such. Only real solution would be to patch the native shells with a "blackscreen layer". Any plans how to deal with that?

**Comment by shockone** [comment]
@jerch, I imagine building the shell in two steps: the first one would be to create a certain level of compatibility with BASH or ZSH, and then to dive deeper and see what can be improved in that world.

**Comment by shockone** [comment]
The `export` command was added.
