### ISSUE TITLE
History autocompletion should suppress suggestions that don't make sense

### ISSUE THREAD

**Issue by shockone** [shockone/black-screen#13]
Having directories

```
~
  dev
    black-screen
  movies
```
and PWD `movies`, we shouldn't display the history entry `cd black-screen`.

**Comment by sleepypikachu** [comment]
Is history useful if you have to read each command to find out what was deleted from history?
If I'm using my history interactively (up, up, enter to repeat the command from two lines ago) then I definitely don't want to have my previous command knocked off the stack contextually.

If I'm using a search (ctrl-r, cd, enter to repeat my last cd command) then I suppose it could be useful to strip out `cd black-screen` since I definitely don't want to cd to that directory but if I have
```
~
    dev
        black-screen
    movies
        tech-talks
            black-screen
```
Then I might just know that it's faster to look back for my cd command I used earlier.

**Comment by shockone** [comment]
Well, in the first case you aren't using history autocompletion, right?

**Comment by sleepypikachu** [comment]
Ah, I understand the intent now.
So how do you decide (at a high level) which history entries should be ignored?

**Comment by shockone** [comment]
I have no idea. It's easy with `cd`, though, but it would be better to have a more general algorithm. Maybe each history entry could remember the directory it was executed in, and then autocomplete only there. We'd strip too much, but it might work.

**Comment by frenchie4111** [comment]
What if the algorithm stripped invalid commands? In the `cd` case it would strip `cd black-screen` if you were in the `movies` directory, as that's not a valid command. 

The problem with your directory based system, is that I often do things that are directory independent, like `export` or `source` and I would auto complete assist on all of those.

**Comment by shockone** [comment]
@frenchie4111, how would I know if a command is invalid?

**Comment by frenchie4111** [comment]
That's a good point. It would have to be on a command / command basis. My only concern is that with directory based autocomplete, we will be suppressing suggestions that would be helpful.

**Comment by shockone** [comment]
Closing as this task it too general. We'll never be able to say it's done.
