### ISSUE TITLE
no support for ctrl+u

### ISSUE THREAD

**Issue by masukomi** [shockone/black-screen#207]
type a line of text, then hit ctrl+u every character before the cursor should be deleted 

if you move the cursor back half way through the line and hit ctrl+u everything after it should remain, and everything before it should be deleted. 

This does not appear to be supported.

**Comment by shockone** [comment]
Hi, @masukomi. Thank you for a bug report. A little tip: it's actually not deleted, but rather "cut" into a special clipboard. You can "paste" from it back using C-y.

I don't think we'll implement this any time soon because it doesn't look that critical (feel free to comment if it is indeed critical for you), but you can use cmd+backspace to delete everything to the beginning for now.
