### ISSUE TITLE
\n in output isn't interpreted.

### ISSUE THREAD

**Issue by shockone** [shockone/black-screen#261]

**Comment by onbjerg** [comment]
Could you elaborate? Is \n not translated into a new line?

**Comment by shockone** [comment]
Exactly, @onbjerg. Try executing `echo "one\ntwo"` in Black Screen and, say, iTerm.

**Comment by kbrock** [comment]
@shockone I ran a few scenarios through mac terminal and black-screen. mac terminal behaved as I would have expected:

**reference**
```bash
# echo "a\nb"
a\nb
# echo -e "a\nb"
a
b
# echo "a\\nb"
a\nb
# echo -e "a\\nb"
a\nb
```

**black-screen**
```bash
# echo "a\nb"
anb
# echo -e "a\nb"
anb
# echo "a\\nb"
a
b
# echo -e "a\\nb"
a\nb
```

**Comment by epallerols** [comment]
Hi,

I tried to run the same scenarios in iTerm2, Terminal and black-screen and I get different behaviours in almost all of them.

After reading this [stackexchange answer](http://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo/219274#219274) it seems that it depends on the implementation of the echo command you have.

**Comment by denieler** [comment]
The behaviour of the echo command depends on the default shell which you have in your OS.
You could check which one you are using by executing the `echo $SHELL` command in your terminal. Black-screen can use `bash` or `zsh` for your commands execution depending on that variable, that's why behaviour can be different for different users.

**Comment by shockone** [comment]
I'm closing this because it seems that now it behaves correctly.
