### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by CGamesPlay** [shockone/black-screen#308]
Hey, I just stumbled upon black screen and I'm really excited about it! I'm also thinking about new ways to interact with terminal programs and I'd love to share work as much as possible.

How does the system work? I can't find any architecture document. My specific questions:

- How would I add support for a new shell?
- How does the terminal program communicate with the shell? Just through the tty or is there an additional channel?
- Have you thought about rich interactive programs?

**Comment by shockone** [comment]
Hey, Ryan. There is no architectural document because it's an early stage of development, and things change quite often, which means such a document would quickly get out of sync. To answer your questions

 * How would I add support for a new shell?

It doesn't make sense to support a new shell (fish, huh?) because we plan to implement our own one. Not because we like to invent bicycles, but because interacting with a shell session doesn't seem to be possible.

* How does the terminal program communicate with the shell? Just through the tty or is there an additional channel?

We create a new session every time you execute something. And close it afterwards.

* Have you thought about rich interactive programs?

Could you tell me more about that? The only thing that slightly resembles that is output decorators (https://github.com/shockone/black-screen/blob/master/src/plugins/GitDiff.tsx or https://github.com/shockone/black-screen/blob/master/src/plugins/JSON.tsx). They receive all the information about a job (a command invocation) and should return the new output, which will replace the old one. The decorator aren't applied by default, you'd need to click a magic wand button (on the right side) to see the decorated output.

![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/2ssxs041.png)

**Comment by CGamesPlay** [comment]
This information is great, thanks. I'm working on a project (hterminal on my github) that operates in a pretty different fashion. The interop seems pretty clear from my perspective: It easy both to make a Decorator to understand HTerminal features, and to make HTerminal understand Black Screen decorators.

My goal with HTerminal is explicitly not to create a new shell, but strictly to enhance existing command-line programs with new features. If you're interested, take a look; I'll keep this project posted if anything interesting happens on my end.

**Comment by shockone** [comment]
Whoa, you've fixed the issue with pty.js CPU usage! Kudos, you can't imagine how much time I spent on it. By the way, why do you use child_pty then? Have you read this: https://github.com/chjj/pty.js/issues/103#issuecomment-77676106 ?

**Comment by shockone** [comment]
@CGamesPlay I feel we should unite our efforts, but I can't suggest anything specific right now.

**Comment by CGamesPlay** [comment]
child_pty and pty.js looked pretty identical after the CPU bug was fixed, and I liked the API of child_pty slightly more. I wouldn't worry about it taking an extra thread to watch the file descriptors... it uses an entire process just to run the other shell, and another process to power the chrome renderer... an extra thread hardly seems worth sweating over. Still, child_pty is isolated to a single file so it would be easy to swap out.

Thanks again for the info!
