### ISSUE TITLE
Enter key does not work

### ISSUE THREAD

**Issue by corymickelson** [shockone/black-screen#364]
Just installed. Terminal opens, can type into terminal but enter does nothing.

**Comment by jredville** [comment]
I ran into this as well and opened up the dev tools. Discovered the following error on every keypress. Happy to provide any info needed to help debug or repro

```
/Users/jdeville/proj/black-screen/compiled/src/views/4_PromptComponent.js:5 Uncaught (in promise) Can't parse alias line:     && bundle package \rejected @ /Users/jdeville/proj/black-screen/compiled/src/views/4_PromptComponent.js:5
```

**Comment by sammous** [comment]
Same is happening to me, enter key does not work.
This error pops up:
![screenshot 2016-05-24_09-28-45](https://cloud.githubusercontent.com/assets/7331072/15495729/0036afe2-2192-11e6-9690-7bdbf62eecd9.png)

**Comment by lazywithclass** [comment]
It seems to me that the problem is here: https://github.com/shockone/black-screen/blob/master/src/Aliases.ts#L15

If you try to comment https://github.com/shockone/black-screen/blob/master/src/Aliases.ts#L27 it should work. I might be really wrong here but my assumption as newbie of this project (I discovered this a couple hours ago), is that it assumes `lines` to be an `Array` composed by `=` separated `String`s.

In my case it's not.

**Comment by shockone** [comment]
@lazywithclass to import all your aliases.

**Comment by lazywithclass** [comment]
I see. I still had those even without the `source`ing though... but I'm probably missing something. Thanks for this.
