### ISSUE TITLE
stops responding - dev tools says uncaught error watch

### ISSUE THREAD

**Issue by wdiechmann** [shockone/black-screen#378]
If I navigate to a Ruby On Rails project - like 

`cd /Users/Walther/Projects/Rails/tyres`

and I try to give any command - BS stops responding (in fact it looks like it stops responding the moment it hits the directory)

Dev Tools says:
`events.js:160 Uncaught Error: watch /Users/Walther/Projects/Rails/tyres/tmp/cache/assets/sprockets/v3.0/xW EMFILE`

**Comment by GuruM** [comment]
+1, I think because the directories contain too many files?

**Comment by fcortes** [comment]
I was getting the same error so I deleted everything in that directory (it was a a bunch of sprockets cache files) but I'm still getting an error
`Error: EMFILE: too many open files, scandir '/Users/...'`
It seems that BS is trying to open (?) too many files, maybe something around [here](https://github.com/shockone/black-screen/blob/master/src/utils/Common.ts#L50). I'm not very experienced with TypeScript, otherwise I'd try to fix it myself.
[Here](http://stackoverflow.com/a/15934766/356925) they say that replacing `fs` with [`graceful-fs`](https://github.com/isaacs/node-graceful-fs) could fix these issues

**Comment by dhensche** [comment]
I'm getting the same exception, but it only started when I `cd`ed into a git repository. Not sure if that is relevant or not. In the console I see a bunch of the errors @wdiechmann mentioned, as it looks like it is trying to watch all of the files recursively within my repository.

**Comment by shockone** [comment]
Fixed.
