### ISSUE TITLE
Questions regarding color display in vim and neovim

### ISSUE THREAD

**Issue by sayingandparsing** [shockone/black-screen#459]
I'm wondering about the implementation and status of coloring in terminal applications. When I run vim, syntax coloring is applied, but the colors are different from the ones displayed in the terminal. 
In neovim, which I have set to display in true color (24-bit), there's no coloration, so all text appears in the default grey.
I know that coloring hasn't been completely implemented (which is totally understandable. there's a lot to do, and for a tool as powerful as black-screen, I'm willing to wait), but I have a couple questions.
1) Are there any plans to support true color?
2) Are the colors used in vim based on defaults that are listed somewhere in the code?

**Comment by shockone** [comment]
Basic color (like red, green, etc.) differ because they are customizable. You can even map red color to green, if you wish. In Black Screen they're defined here https://github.com/shockone/black-screen/blob/master/src/views/css/colors.ts#L14-L23

As of 24-bit support, we already have an issue https://github.com/shockone/black-screen/issues/139

**Comment by shockone** [comment]
Added 24-bit support in v0.0.32.

**Comment by sayingandparsing** [comment]
Thanks you so much shockone!
