### ISSUE TITLE
Displaying autocomplete options with values

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#644]
I am developing an auto-completion provider and I would like to show available option-values for command options that require values. For example, if a user enters "git commit --cleanup=" the auto-complete ideally suggests the options "strip, whitespace, verbatim, scissors & default".

In an older version of black-screen there was an optionWithValue class that provided this feature. Unfortunately I couldn't work out how to implement since the auto-complete functionality has been updated.

Is there a way to do this?

**Comment by shockone** [comment]
Hi. There is con convenient way because `--cleanup=strip` is one token, but you can check if the token starts with `--cleanup=` and then return suggestions with `value` like `--cleanup=strip` and `displayValue` like `strip`. This way you'll see only the word after the equal sign in the autocompletion popover, but when you press tab, the whole token will get replaced properly.

**Comment by mkenne11** [comment]
Thanks @shockone - I think I follow what you mean. It looks like the "branchAlias" suggestion provider does something similar:
https://github.com/shockone/blackscreen/blob/master/src/plugins/autocompletion_providers/Git.ts#121 

I will try and implement this.

**Comment by shockone** [comment]
You're welcome. Don't hesitate to ask, if you have any issues. Also, maybe a more appropriate channel of communication would be https://gitter.im/shockone/black-screen
