### ISSUE TITLE
OS X only?... Really?

### ISSUE THREAD

**Issue by yonas** [shockone/black-screen#720]
It's interesting that you chose to restrict pre-1.0 development to a proprietary operating system. 

I don't have a Mac, and have no plans on buying one, but would love to be testing out Black Screen.

**Comment by drew-gross** [comment]
People have reported that it mostly works on linux (which is about as much as I can say for mac as well :P), so feel free to test it out on your machine. I image the reason is that the main developers mostly use macs, and developing for an operating system you don't use is tedious and slow.

**Comment by yonas** [comment]
Thanks @drew-gross, you're probably right!

`<rant>`
I just think that this is becoming a trend within the open source community lately, and it's not a good thing.

How can I get excited about an open source project if I have to buy software to get started?

OS X uses a lot of open source software, but in the end, is not open source itself until I can legally install it within Virtualbox or KVM for free.
`</rant>`

**Comment by minecrawler** [comment]
@yonas : ya, but its opensource. Do not complain about free stuff. If you want to get it running on your OS, download the source, fix it and make a PR. It's just JS on Node.JS inside Electron, which, in theory, can run on most desktop operation systems.

**Comment by yonas** [comment]
@minecrawler Thanks, but complaining about free stuff is how we make improvements in the open source community :)

My rant is about culture. No amount of forking code will fix that, but discussions can.

Second, don't assume that I have the ability to work with the code just because I'm here, or because I'm a software developer. My rant is every bit as valid whether I'm personally capable of fixing this myself, or not. The "put up or shut up" attitude isn't going to help here.

I think there's a perception that, if enough people already have OS X laptops, then we don't really need to bother about everyone else. I really rather not see that become ingrained in the open source community, so I'm speaking up about it now.

Anyway, closing this issue since @drew-gross addressed it very well.

**Comment by LogoiLab** [comment]
OSX gives a bad name to unix. I agree that open source software should be created for open source platforms using open source tools FIRST and then redeveloped for other systems.

**Comment by minecrawler** [comment]
@yonas They write in their README that there will be support for other platforms. Again, if you use Windows, which platform would you target first? Linux? Even if you don't have it installed? What about BSD? And Haiku? Plan9? ReactOS? Why not choose one of them?

Imho it is fine if they choose macOS as the initial platform until the 1.0.0 release, as long as they work on the tool. Just talking about it won't solve a thing :)

**Comment by yonas** [comment]
I don't mind if you're part of the open source community and you first publish to Linux, *BSD, Haiku, Plan9, etc. But not a propriety operating system that requires me to legally pay money for their operating system. That goes against the open source movement and does not belong in the open source community.

Yes, I'm glad that they'll eventually support other platforms, but it would have been better to start with a non-proprietary operating system.

One might think - why not steal the software? First, I rather work on software projects where I'm not required to break the law. Second, I might have enough money to purchase the software (and possibly hardware, in this case, an Apple laptop), but many others can't, which means this becomes a real barrier to participation.

To some people, "open source software" is simply software you don't have to pay for - nothing more. For me, and many others, it's much more than that. It's a philosophy. It's a way of sharing ideas and building better technologies on a global scale - now and into the future. I only deploy open source software at the companies I work for, and I only recommend open source software for the clients I work with.

Talking about this will hopefully begin a conversation that will lead to decreasing this trend. There's a time for coding and there's a time for conversation. This is a time for conversation. If you don't like that, then you're free to go back to coding! :)

**Comment by sedwards2009** [comment]
@yonas  What you have discovered is the difference between Open Source and Free Software. You would like Black Screen to follow Free Software principles more is what you are saying.

**Comment by minecrawler** [comment]
@yonas Don't get me wrong, I would even welcome a law which makes software developers publish software to at least one open platform. But this is opensource and most developers here use a lot of their free time to work on code you can use and modify for free. It's the same for me, after all! That's why I really appreciate what they do and if they decide to stay with what they have and even offer to make stuff more convenient to you in the future, then you should accept that decision gladly.

Personally, I do not like Apple and lately I came to hate Microsoft. Yes, I use Gentoo Linux. Yes, because of that I target Linux first. But if I still were on Windows, I would stay on Windows for development. I am just a human, the developers of this project are just humans, and you do not program and maybe because of that do not see just how much work such an application  is and how many hours of their time - which they could spend with their loved ones, gaming, vacation, w/e - they spend on this project just so that you can be the tiniest bit more lazy when using the console. OSS (and Free Software for that matter) are not about some people working their ass off for other for free, but rather to establish a community of joint development and improvement. They do a great part writing this application, so someone else can do their part and make sure it runs on whatever OS they use.

**Comment by yonas** [comment]
@sedwards2009 Thanks, yes, I think that's right.

**Comment by yonas** [comment]
@minecrawler Thanks for your response, I appreciate it. I am a fellow programmer, actually :) I began programming when I was 12 with C/C++ - which is when I first began using Slackware and FreeBSD - earned a Bachelors of Computer Science from the University of Waterloo, and have been programming with open source software pretty much every day for the past 20 years. Because of that, I understand the time investment very well and appreciate their contributions, but there's room for improvement.

> They do a great part writing this application, so someone else can do their part and make sure it runs on whatever OS they use.

Because Black Screen is freely available, it's not a total loss that they develop only for OS X prior to 1.0 - but they could do better. That's my whole message. It would be better if I didn't have to own a proprietary operating system to immediately gain the benefits of Black Screen. Again, as Drew mentioned, Black Screen in particular seems to run fine for other operating systems - which is great! - but it would be better if the developers completely avoided developing only for a proprietary operating system prior to 1.0 in the first place.

These days, you can run your favourite flavour of Linux/*BSD in Virtualbox, even on OS X. It would be great if they took advantage of that to develop for Linux/*BSD prior to 1.0, even while using their Macbook.

**Comment by Rafi993** [comment]
If this works in linux then please update README.md saying it does rather than saying it runs in os x only. when I first saw this repo I didnt bother to try it because I use linux. Then after sometime I came across this thread after which I realized that I could use it in linux too. Plus doing so will atract developers who use linux to contribute to this project to speeding it up.
